---
- hosts: all
  remote_user: kube
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
     - name: install containerd
       shell: |
               sudo apt install containerd -y

     - name: Create containerd config file
       shell: |
               sudo mkdir -p /etc/containerd
               containerd config default | sudo tee /etc/containerd/config.toml > /dev/null
               sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
               sudo systemctl restart containerd
