---
- hosts: all
  tasks:
    - name: cleaning up install
      shell: |
              sudo kubeadm reset
              sudo rm -rf /etc/kubernetes/
              sudo rm -rf $HOME/.kube
              sudo rm -rf /etc/cni/net.d
              sudo apt-get purge -y kubeadm kubectl kubelet kubernetes-cni kube*
              sudo apt-get autoremove -y
              sudo iptables -F
              sudo docker rm -f $(sudo docker ps -aq)
              sudo docker rmi $(sudo docker images -q)

